#!/usr/bin/env python3
# Generated by scripts/build_workbooks.py; shared runtime is bundled locally.
from pathlib import Path
from _workbook import create_main


if __name__ == "__main__":
    raise SystemExit(create_main(Path(__file__).resolve().parent.parent))
