#!/usr/bin/env python3
"""Generate or check native skill entry points without duplicating skill bodies."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
LOCATIONS = (".agents/skills", ".claude/skills")
MANIFEST = ".agents/skill-adapters.json"
NAME = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")


def digest(content: bytes) -> str:
    """Keep ownership checks stable across Git's LF and CRLF checkout modes."""
    return hashlib.sha256(content.replace(b"\r\n", b"\n")).hexdigest()


def local_path(root: Path, relative: str) -> Path:
    path = root / relative
    if Path(relative).is_absolute() or ".." in Path(relative).parts:
        raise ValueError(f"Expected a repository-relative path: {relative}")
    for part in (path, *path.parents):
        if part == root:
            break
        if part.is_symlink():
            raise ValueError(f"Refusing to manage a symlink: {part}")
        if part != path and part.exists() and not part.is_dir():
            raise ValueError(f"Expected an adapter directory, found a file: {part}")
    return path


def adapter_path(value: str) -> bool:
    parts = Path(value).parts
    return (
        len(parts) == 4
        and "/".join(parts[:2]) in LOCATIONS
        and NAME.fullmatch(parts[2]) is not None
        and parts[3] == "SKILL.md"
        and value == "/".join(parts)
    )


def load_manifest(root: Path) -> dict[str, str]:
    path = local_path(root, MANIFEST)
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or type(data.get("schema_version")) is not int or data["schema_version"] != 1:
        raise ValueError(f"{MANIFEST}: expected schema_version 1")
    entries = data.get("files")
    if not isinstance(entries, dict):
        raise ValueError(f"{MANIFEST}: expected a files object")
    result: dict[str, str] = {}
    for name, checksum in entries.items():
        if not isinstance(name, str) or not adapter_path(name):
            raise ValueError(f"{MANIFEST}: invalid managed path {name!r}")
        if not isinstance(checksum, str) or not re.fullmatch(r"[a-f0-9]{64}", checksum):
            raise ValueError(f"{MANIFEST}: invalid checksum for {name}")
        result[name] = checksum
    return result


def render_adapters(root: Path) -> tuple[dict[str, str], int]:
    skills = local_path(root, "skills")
    sources = sorted(skills.glob("*/SKILL.md"))
    if not sources:
        raise ValueError("No canonical skills found in skills/; refusing to remove adapters")
    rendered: dict[str, str] = {}
    for source in sources:
        local_path(root, source.relative_to(root).as_posix())
        name = source.parent.name
        if len(name) > 64 or not NAME.fullmatch(name):
            raise ValueError(f"Invalid canonical skill directory name: {name}")
        content = source.read_text(encoding="utf-8")
        match = re.match(r"\A---\n(.*?)\n---\n", content, re.DOTALL)
        if not match:
            raise ValueError(f"{source}: missing YAML frontmatter")
        header = match.group(1)
        declared = re.findall(r"^name:[ \t]*([^\n]+)$", header, re.MULTILINE)
        descriptions = re.findall(r"^description:[ \t]*([^\n]+)$", header, re.MULTILINE)
        if len(declared) != 1 or declared[0].strip().strip("\"'") != name:
            raise ValueError(f"{source}: frontmatter name must match its directory")
        if len(descriptions) != 1 or not descriptions[0].strip().strip("\"'"):
            raise ValueError(f"{source}: a nonempty description is required")
        body = (
            f"---\n{header}\n---\n\n"
            "<!-- Generated by scripts/sync_skills.py. Do not edit this adapter. -->\n\n"
            f"# {name}\n\n"
            f"Read and follow the [canonical skill](../../../skills/{name}/SKILL.md)\n"
            "before starting this workflow. This file is only a discovery entry point.\n\n"
            f"The canonical directory is `skills/{name}/` relative to the repository\n"
            "root. Resolve all relative references, templates, scripts, and skill-local\n"
            "commands there, not in this adapter directory. Follow any explicit\n"
            "repository-root command instructions in the canonical skill.\n\n"
            "Use the full Venture checkout. Do not install this adapter on its own;\n"
            "install the canonical skill directory for standalone use.\n"
        )
        for location in LOCATIONS:
            rendered[f"{location}/{name}/SKILL.md"] = body
    return rendered, len(sources)


def synchronize(root: Path, check: bool = False) -> None:
    root = root.resolve()
    expected, count = render_adapters(root)
    previous = load_manifest(root)
    problems: list[str] = []
    for relative in sorted(set(expected) | set(previous)):
        path = local_path(root, relative)
        if path.exists():
            current = path.read_bytes()
            if relative not in previous:
                problems.append(f"Unmanaged file would be overwritten: {relative}")
            elif digest(current) != previous[relative]:
                problems.append(f"Managed adapter has local edits; preserve or reconcile them first: {relative}")
            if check and (relative not in expected or digest(current) != digest(expected[relative].encode("utf-8"))):
                problems.append(f"Stale adapter: {relative}")
        elif check and relative in expected:
            problems.append(f"Missing adapter: {relative}")
    checksums = {name: digest(content.encode("utf-8")) for name, content in expected.items()}
    if check and previous != checksums:
        problems.append(f"{MANIFEST} is missing or stale")
    if problems:
        raise ValueError("\n".join(problems))
    if not check:
        for relative in sorted(set(previous) - set(expected)):
            path = local_path(root, relative)
            if path.exists():
                path.unlink()
                if not any(path.parent.iterdir()):
                    path.parent.rmdir()
        for relative, content in expected.items():
            path = local_path(root, relative)
            encoded = content.encode("utf-8")
            if not path.exists() or digest(path.read_bytes()) != digest(encoded):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(encoded)
        manifest = local_path(root, MANIFEST)
        manifest.parent.mkdir(parents=True, exist_ok=True)
        content = json.dumps({"schema_version": 1, "files": checksums}, indent=2, sort_keys=True) + "\n"
        if not manifest.exists() or manifest.read_text(encoding="utf-8") != content:
            manifest.write_text(content, encoding="utf-8")
    print(f"{'Checked' if check else 'Synchronized'} {len(expected)} adapters for {count} canonical skills.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report missing, changed, or stale adapters without writing")
    args = parser.parse_args()
    try:
        synchronize(ROOT, check=args.check)
    except (OSError, UnicodeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        if args.check:
            print("Run python3 scripts/sync_skills.py after resolving any ownership conflicts.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
